# Generated by Django 4.2.2 on 2023-06-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.PositiveIntegerField()),
                ('Imagen', models.FileField(upload_to='')),
                ('Descripcion', models.CharField(max_length=50)),
                ('Opiniones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarroCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producto')),
            ],
        ),
    ]
