# Generated by Django 4.2.2 on 2023-06-21 06:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_alter_categorias_idcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='Fecha',
            field=models.DateField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
