# Generated by Django 4.2.2 on 2023-06-21 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_movimientos_fecha_alter_movimientos_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoscategorias',
            name='IdCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcategoria', to='shop.categorias'),
        ),
        migrations.AlterField(
            model_name='productoscategorias',
            name='IdProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idproducto', to='shop.productos'),
        ),
    ]
